[package]
name = "overkill-chat"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "~2.27.0"
socks = "0.3.3"
snow = "0.8.0"
ring = "0.16.20"
